# Generated by Django 3.2.3 on 2021-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='KinopoiskMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoisk_id', models.PositiveIntegerField(verbose_name='Идентификатор фильма на Кинопоиске')),
                ('title_ru', models.CharField(db_index=True, max_length=500, verbose_name='Название по-русски')),
                ('title_en', models.CharField(db_index=True, max_length=500, verbose_name='Название по-английски')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('countries', models.ManyToManyField(related_name='country_movies', to='movie.Country', verbose_name='Страна')),
                ('genres', models.ManyToManyField(related_name='genre_movies', to='movie.Genre', verbose_name='Жанры')),
            ],
        ),
    ]
