# Generated by Django 3.2.3 on 2021-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinopoiskmovie',
            name='kinopoisk_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Идентификатор фильма на Кинопоиске'),
        ),
    ]
