# Generated by Django 3.2.3 on 2021-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_kinopoiskmovie_kinopoisk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinopoiskmovie',
            name='title_en',
            field=models.CharField(max_length=500, verbose_name='Название по-английски'),
        ),
    ]
